### ISSUE TITLE
Training - error

### ISSUE THREAD

**Issue by bidakos** [cloud-annotations/training#10]
I get the following error, when I run "python -m wml.start_training_run"

from object_detection.protos import string_int_label_map_pb2
training-UGIxBkrmR: ImportError: cannot import name 'string_int_label_map_pb2'

Any help? @bourdakos1

**Comment by MatthewGleeson** [comment]
I'm getting the same error.

**Comment by bidakos** [comment]
@MatthewGleeson Are you based in Europe? I was using the us object storage endpoint and the eu ml endpoint. I moved the ml endpoint to the us server and it worked.

**Comment by MatthewGleeson** [comment]
I fixed it, I didn't have protobuf installed so I had to run:
`brew install protobuf`
