### ISSUE TITLE
Support for training on AWS

### ISSUE THREAD

**Issue by sachinshelke** [cloud-annotations/training#104]
Hi,

I think we should provide support for training model on AWS instance as well.
Since last few weeks there are so many changes happening on IBM cloud and behind the scene IBM uses AWS itself.

It would be really helpful to keep scripts consistent and time to time we can provide better feature rather changing existing feature.

Understand that, upgrading existing feature is part of development cycle. However, providing more feature would create future for one strong library.

Any thoughts are welcome 
@bourdakos1 plz suggest the way if i can help. (I'm very much new bee for ML but I can try my best to support for enhancement)

Thanks

**Comment by bourdakos1** [comment]
IBM doesn’t use AWS, IBM’s object storage uses a similar enough structure to s3 buckets so you can use the commands interchangeably. If you specify aws s3 credentials and endpoint in the command line tool it will use your aws bucket, but the training of the model uses Watson machine learning. I’m not sure if AWS has a similar service, but it would take a lot of work for me to build. And the same functionality could be asked for google cloud and azure. I’m open to pull requests though :)

Lastly you can export the annotations from cloud annotations and use them on any cloud platform
