### ISSUE TITLE
"Model done", but always "in progress of training"

### ISSUE THREAD

**Issue by kurish** [cloud-annotations/training#106]
Hi, it all was good since today. But now, i'm going to train model in usual way:

Run "cacli train", logs are empty, and finally after some time "success Model files saved to bucket."
And when i want "cacli download", i've got "Model is still training, would you like to monitor progress? (yes) "

All screens attached. Some advices?

Thank you!

<img width="1389" alt="Screen Shot 2019-08-08 at 6 49 52 PM" src="https://user-images.githubusercontent.com/4609588/62717877-60a0c180-ba0d-11e9-8840-7d2955c882b4.png">
<img width="567" alt="Screen Shot 2019-08-08 at 6 49 42 PM" src="https://user-images.githubusercontent.com/4609588/62717878-61395800-ba0d-11e9-822e-e92e6b093786.png">
<img width="805" alt="Screen Shot 2019-08-08 at 6 49 28 PM" src="https://user-images.githubusercontent.com/4609588/62717879-61395800-ba0d-11e9-8a3a-5739b885fd54.png">

**Comment by bourdakos1** [comment]
I think the free tier gpus were under heavy load today, maybe try again tomorrow and see if it works. I’ll also look into it on my end

**Comment by kurish** [comment]
K, will try today, thanks

**Comment by kurish** [comment]
Have you tried on your side?

**Comment by sachinshelke** [comment]
Yes this is happening with me as well. 
Have training different models 4 times and after model generated it is still showing in progress.
This issue appears either IBM changes from username & password to instance key or some changes in training script. _not sure_

**Comment by bourdakos1** [comment]
If you run “cacli list” what does it say?

**Comment by kurish** [comment]
Thanks for reply, so we got next:
<img width="789" alt="Screen Shot 2019-08-12 at 4 07 14 PM" src="https://user-images.githubusercontent.com/4609588/62867166-50ddf180-bd1b-11e9-9ed5-07a9b7ee4ccd.png">

As we see, model can be downloaded through 4 days))
Unfortunately, it's probably ibm problem with computing power(
