### ISSUE TITLE
Cannot complete training 

### ISSUE THREAD

**Issue by rockleona** [cloud-annotations/training#108]
![1565435181943](https://user-images.githubusercontent.com/34214497/62821182-60d2c580-bba3-11e9-9649-fb6858437f37.jpg)

The first model i trained seems like it doesn't complete yet,
it's weird for me, 'cause i've trained a model before(on July 7),and the progress ran very quick.

So, i enter `cacli progress <model_id>` to see how it have done.
And this is what i got.
Can anyone teach me how to solve in this situation? Thanks!
![1565435156274](https://user-images.githubusercontent.com/34214497/62821230-58c75580-bba4-11e9-9f48-ef1478449d00.jpg)

**Comment by bourdakos1** [comment]
The k80 gpus have had an unusually high usage the last couple day, so a lot of people have been getting pending and failed models

**Comment by rockleona** [comment]
okay... :(
BTW, is there any way to cancel the models training which were error?
Thanks a lot again!

**Comment by bourdakos1** [comment]
Failed status means the training run was cancelled. It’s only counting hours when it’s status is “running”. There’s a way to cancel the runs, but I’m not sure if it’s implemented in cacli yet. You can open up another issue for that and I’ll get to work on adding that in

**Comment by rockleona** [comment]
Sure, if I need  that i'll open it .
Thanks for your magnificent work and answering. They help me a lot!
thanks again :)
