### ISSUE TITLE
[object-detection-react] Redefine video source to .m3u8

### ISSUE THREAD

**Issue by RickBadKan** [cloud-annotations/training#128]
Initially on [cloud-annotations/object-detection-react#10](https://github.com/cloud-annotations/object-detection-react/issues/10).

I'd like to change the video source from my camera to a Nest cam public link (`.m3u8`). I tried to change the source argument to a URL but it didn't work out.

**Comment by bourdakos1** [comment]
Try this out: https://github.com/cloud-annotations/object-detection-live-stream

**Comment by RickBadKan** [comment]
Thank you, I'll give it a try!
