### ISSUE TITLE
Add warnings that not enough images are labeled

### ISSUE THREAD

**Issue by bperel** [cloud-annotations/training#142]
Hello,

I am training to train my first model using the image classifier but the training seems to fail and the logs are almost empty. What can I do to debug the issue?

```bash
bperel@home:/var/www/html/ml$ cacli train
(Using settings from config.yaml)
success Training run submitted.

Model ID:
┌────────────────┐
│ model-h7gb3psd │
└────────────────┘

Would you like to monitor progress? (yes) 

error Training failed.
bperel@home:/var/www/html/ml$ cacli logs model-h7gb3psd

──────────────────────────────────

   Monitoring model-h7gb3psd...

──────────────────────────────────

training-JP07A50ZR: 
training-JP07A50ZR: 
training-JP07A50ZR: 
training-JP07A50ZR: 
training-JP07A50ZR: 
training-JP07A50ZR: 
training-JP07A50ZR: 1

───────────────────────

   Log monitor done.

───────────────────────

bperel@home:/var/www/html/ml$ cacli progress model-h7gb3psd
✨ Done.
bperel@home:/var/www/html/ml$ cacli download model-h7gb3psd
Training was canceled or failed.

bperel@home:/var/www/html/ml$ cat config.yaml
buckets:
  training: mybucket
  output: mybucket
name: mybucket
```

where `mybucket` is the actual name of the bucket that I used.

**Comment by bourdakos1** [comment]
what version of cacli are you using?

**Comment by bperel** [comment]
Version 1.1.12

**Comment by bperel** [comment]
Any information that I could provide to help debugging?

**Comment by bourdakos1** [comment]
Uhh can you try running cacli list? Also, have you tried running it again?

**Comment by bperel** [comment]
Yes, I tried running it again just now with the same result. Something wrong with my bucket perhaps? It contains 100 JPEG pictures but I don't see what could be wrong with them.

`cacli list` gives :
```bash
 name                                 model id            status          submitted
 mybucket                             model-rya8fze8      error          2 days ago
 mybucket                             model-h7gb3psd      error          2 days ago
 mybucket                             model-116b36nb      error      14 minutes ago
 mybucket                             model-hc88fp3a      error       5 minutes ago
```

I don't know if it's relevant, but the status of the last one was `running` until 3-4 minutes after `cacli train` stopped with the message `error Training failed.` ; then it became `error` like shown above.

**Comment by bourdakos1** [comment]
Is there an _annotations.json file?

**Comment by bperel** [comment]
Locally? No, I only have `config.yaml` and 2 files for respectively the ML and storage credentials.

**Comment by bourdakos1** [comment]
I mean in your bucket

**Comment by bperel** [comment]
Yes, here it is :
[_annotations.json.txt](https://github.com/cloud-annotations/training/files/3800429/_annotations.json.txt)

**Comment by bourdakos1** [comment]
Oh, classification! Ill test that out. The only thing that comes to mind is that possibly the “/” in the label is an illegal character, but that error should be displayed in the logs

**Comment by bourdakos1** [comment]
@bperel is this still an issue? I'm unable to reproduce

**Comment by DemirKorac** [comment]
@bourdakos1 Could you reopen this issue? I am having an identical issue.
[_annotations .json.txt](https://github.com/cloud-annotations/training/files/3954894/_annotations.json.txt)

cacli version 1.2.1
Ubuntu 18.04

**Comment by bourdakos1** [comment]
Are there and PNGs in the dataset?

**Comment by bperel** [comment]
Yes, the issue still happens with similar output. On my side it's only JPEG pictures in the bucket

**Comment by DemirKorac** [comment]
Same thing here, no PNGs

**Comment by bourdakos1** [comment]
Do you mind running:
```
cacli export
```
And share the content?

**Comment by bourdakos1** [comment]
Oh actually, now that I think of it, you have a lot of labels, but only 100 images? You might not have enough images per label. There’s not a hard number on how many you need, but it normally crashes with no warnings if you have less then 20 images per label

**Comment by bourdakos1** [comment]
@DemirKorac you definitely don’t have enough images

**Comment by DemirKorac** [comment]
Strange, I have tried training again 2 days ago with no success maybe 5 or 6 times, and then all of a sudden on the ~7th attempt training was successful and the model was recognizing as expected, even with the low amount of images/label ratio that I have.
Needs more investigating but very strange behavior.

**Comment by bourdakos1** [comment]
yea, it _can_ work with less than 20 images, but it's very sporadic as you've noted. I haven't had the issue with more than 20 images though

**Comment by DemirKorac** [comment]
Ok, noted. Thanks for the advice, much appreciated! @bourdakos1

**Comment by bperel** [comment]
I finally found the issue! Some of labels had slashes in them, which I guess created issues with paths. Here is the part of the log corresponding to the issues:

```
I0409 11:53:43.611317 139961353692992 retrain.py:181] Looking for images in 'fr'
W0409 11:53:43.611498 139961353692992 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:184: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0409 11:53:43.647344 139961353692992 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:186: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

W0409 11:53:43.647614 139961353692992 retrain.py:186] No files found
I0409 11:53:43.647780 139961353692992 retrain.py:181] Looking for images in '3HI'
Traceback (most recent call last):
  File "/opt/anaconda/envs/wmlce/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda/envs/wmlce/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/job/model-code/src/classification/retrain.py", line 1313, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/job/model-code/src/classification/retrain.py", line 981, in main
    FLAGS.validation_percentage)
  File "/job/model-code/src/classification/retrain.py", line 184, in create_image_lists
    file_list.extend(tf.gfile.Glob(file_glob))
  File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: data/3HI; No such file or directory
CACLI-TRAINING-FAILED
Training exited with error code 1
Failed: learner_exit_code: 1
```

My label was called "fr/3HI", and as you can see it split the label into 2 parts, which failed. Once I renamed my label to "fr-3HI", the training worked.

**Comment by bourdakos1** [comment]
ah that makes sense, good to know :)

**Comment by bourdakos1** [comment]
We can leave this open

**Comment by bourdakos1** [comment]
warnings have been added when trying to train in the UI with under 20 images
