### ISSUE TITLE
Can you send me an example file of labels.json?

### ISSUE THREAD

**Issue by DarkNavrel** [cloud-annotations/training#15]
Hello, I was able to execute all the steps of the tutorial, but during the training I get the message:
ModuleNotFoundError: No module named 'object_detection'
I already have the training data I did in the past on a local machine, but in the model_web folder it does not contain the labels.json file, only labels.txt. I see that my project is very simple with only one category, you would not mind sending me an example of labels.json? So I can manually create one to solve my problem

**Comment by bourdakos1** [comment]
I don’t think the “object_detection” directory was successfully created, was running “setup.py object_detection” successful?

**Comment by DarkNavrel** [comment]
yes, it was installed, but from what I could see, since the tensorflow already installed on the machine via conda install, there may be some incompatibility. But since I already have a trained and converted model I would use it, I just lack the labels.json

**Comment by bourdakos1** [comment]
Oh interesting, the model trained? The labels.json is just an array of
labels, so for example:
[ “Label Name” ]

**Comment by DarkNavrel** [comment]
Thanks for the answer, I did, however another solution in my case of only one class was instead of using label.json, just use the class name in code. Actually it was incompatibility in the Tensorflow Patch, in my computer it is installed with Anaconda Package, I believe that a clean installation would work, but it already had the trained model
