### ISSUE TITLE
add auto labeling

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/training#152]
Users can upload their model to the bucket (or if they stored the the training output to their bucket) The client will give the user an `auto label` button that will use the model to detect objects in the selected photo.

pressing the autolabel button should prompt the user with the new labels highlighted allowing them to confirm or reject the propositions. 

Possibly have an option to autolabel the entire dataset at once with a specified confidence?

I'm thinking almost a find and replace UI. i.e.
keep tapping enter to `confirm` or `skip` labels in an image, then move onto the next image
or press the `confirm all in image` or `confirm all in dataset` button

**Comment by sachinshelke** [comment]
+1

Can it be possible to prioritize this enhancement. 
This is one of the most useful feature for everyone. And IBM Watson started with auto labelling but their labelling process is very very slow.

**Comment by bourdakos1** [comment]
I can try my best, shouldn't be too hard 😬

**Comment by sachinshelke** [comment]
Hi @bourdakos1 , 
Could you please mention expected time for this feature.

**Comment by bourdakos1** [comment]
I wouldn’t expect it any sooner than the end of December. If you have any experience with react, I’m welcome to outside help

**Comment by bourdakos1** [comment]
Originally I was going to load models from object storage, but after looking at the tensorflow.js docs I think we also have other options. 

The user could upload models directly to the tool and be persisted to localstorage/indexeddb. The drawback would be that you would only be able to use the model on the browser that you uploaded the model to. The perk would be that you could easily use any model with any bucket

**Comment by bourdakos1** [comment]
Here's mock ups of what auto label will most likely look like
![autolabel1 copy](https://user-images.githubusercontent.com/4212769/69770811-67884700-1158-11ea-858f-78782e3c4782.png)

![autolabel2](https://user-images.githubusercontent.com/4212769/69770777-458ec480-1158-11ea-9efa-4023442e794e.png)

**Comment by sachinshelke** [comment]
Second option looks more prominent as user can outside model to auto-label.
I do not have experience in React but will try locally. If got any success will raise a pull request for your review.

**Comment by bourdakos1** [comment]
loading the model seems to block the UI so I will load it after clicking auto label

**Comment by bourdakos1** [comment]
✅Auto label UI is pretty much done
✅I'm able to load the model from the object storage
⏹Need to implement the actual labeling logic

**Comment by bourdakos1** [comment]
@sachinshelke auto labeling is more/less complete.

I think the workflow could be ironed out a bit more to make things more efficient.

At the moment, to use the feature you need to upload a `model_web` folder to the root of your object storage bucket. Eventually you will be able to upload models directly to the tool or use a model stored directly from training.

**TODO:**
⏹ Label lots of images to find places to smooth out user experience 
⏹ Add keyboard shortcuts
⏹ Upload model through the tool
⏹ Use model from any location in bucket

**Comment by bourdakos1** [comment]
You can try out the feature at: https://stagingannotations.us-east.containers.appdomain.cloud/

**Comment by sachinshelke** [comment]
@bourdakos1 Awesome. It work as it required.
I think it is good to be put in production.

One more item in **TODO**
*   Allow modifying / adjusting auto labelled box

**Comment by bourdakos1** [comment]
I think I will release this by end of the day

Here's future update **TODO**s:
⏹ Allow modifying boxes
⏹ Allow drawing a new box
⏹ add a previous button
⏹ highlight all auto predicted boxes when hovering label all
⏹ add accept button to the box itself

**Comment by bourdakos1** [comment]
Auto labeling is now live, I'll close this issue and open a new one requesting enhancements
