### ISSUE TITLE
Import xml annotations

### ISSUE THREAD

**Issue by gamcoh** [cloud-annotations/training#17]
Is there a way to import into IBM cloud annotations my images with my xml annotations files?

**Comment by bourdakos1** [comment]
Not at the moment, but if you write a script to convert the xml to a file named _annotations.json with the proper format, that would work

**Comment by bourdakos1** [comment]
I can attach a sample of the json in a few hours

**Comment by gamcoh** [comment]
Alright perfect! could you also tell me how can upload the json file then?
Thanks a lot!

**Comment by bourdakos1** [comment]
You can either use the ibm cloud GUI to upload files to your object storage bucket, or you can use the ibm-cos-sdk

**Comment by bourdakos1** [comment]
Here's a simple example of the json
```
{
  "version": "1.0",
  "type": "localization",
  "labels": ["Label1", "Label2", "Label3"],
  "annotations": {
    "image1.jpg": [
      {
        "x": 0.7255949630314233,
        "x2": 0.9695875693160814,
        "y": 0.5820120073891626,
        "y2": 1,
        "label": "Label1"
      }
    ],
    "image2.jpg": [
      {
        "x": 0.8254101201478743,
        "x2": 1,
        "y": 0.2913716133004926,
        "y2": 1,
        "label": "Label3"
      },
      {
        "x": 0.8845598428835489,
        "x2": 1,
        "y": 0.1829972290640394,
        "y2": 0.966248460591133,
        "label": "Label2"
      }
    ]
  }
}
```

**Comment by bourdakos1** [comment]
It shouldn't be too hard to convert, if you have a sample of your xml annotations I'd be glad to help out

**Comment by gamcoh** [comment]
That's really kind thanks but I think I'll write the conversion script and post it here afterwards.

What does the coordinates stand for? Is it pixel? Is it because the images are resized?

**Comment by gamcoh** [comment]
Here's [the script](https://github.com/gamcoh/Xml2Json/tree/master)

How the json file will be linked to the images?
Do I just need to upload the json file with the name named_annotations.json into my bucket like I did for my images and it will work?

Also, when I uploaded my images into my bucket the platform change the names so there's that too.

And last question, in your json example, I don't understand the coordinates, if mine are pixels can I convert them?

Thanks

**Comment by bourdakos1** [comment]
The coordinates are percentages, so if your image is 300 x 500px
and you have a bounding box that is:
120px from the left
30px from the top
100px wide
20px tall

```
x = 120px / 500px
x2 = 100px / 500px + x
y = 30px / 300px
y2 = 20px / 300px + y
```

**Comment by bourdakos1** [comment]
The cloud annotation tool automatically renames and shrinks images to a reasonable size, so you need to upload images to your bucket through another route. I recommend using the python sdk `https://github.com/IBM/ibm-cos-sdk-python` that way you can have it automatically upload the `_annotations.json` file and all the images immediately after the conversion

**Comment by bourdakos1** [comment]
@gamcoh I made a few changes to your script, can you give me access to commit?

**Comment by gamcoh** [comment]
@bourdakos1, thanks a lot for the codes.

I don't think the upload2bucket.py works well, I get this error:

```
Traceback (most recent call last):
  File "upload2bucket.py", line 39, in <module>
    main()
  File "upload2bucket.py", line 23, in main
    endpoint_url=credentials['url']
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/__init__.py", line 92, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/session.py", line 476, in resource
    config=config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/session.py", line 324, in client
    token_manager=token_manager, config=config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/session.py", line 900, in create_client
    client_config=config, api_version=api_version)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/args.py", line 142, in compute_client_args
    inject_host_prefix=client_config.inject_host_prefix,
AttributeError: 'Config' object has no attribute 'inject_host_prefix'
```

**Comment by bourdakos1** [comment]
hmm, did you install the right version of python-cos-sdk? can you run pip freeze and send the versions for both `botocore` and `ibm-cos-sdk`

**Comment by gamcoh** [comment]
Here are the version:

```
botocore==1.12.26
ibm-cos-sdk==2.3.2
ibm-cos-sdk-core==2.4.4
ibm-cos-sdk-s3transfer==2.4.4
```

**Comment by bourdakos1** [comment]
What did you put for the credentials url

**Comment by gamcoh** [comment]
I've sent to you the credentials by email

**Comment by gamcoh** [comment]
Thanks to @bourdakos1 the scripts for converting the xml to json and uploading the annotations to the Cloud Annotation Tool platform are now good to be used!
