### ISSUE TITLE
model_web folder does not have a model file

### ISSUE THREAD

**Issue by TheFeed** [cloud-annotations/training#183]
After downloading, the "model_web" folder does not have a model. It only has "labels.json." 

However, the "model", "model_ios", and "model_android" folders all have their corresponding models.

**Comment by bourdakos1** [comment]
I just released a few updates, let me double check I didn’t break anything. Do you mind sharing the training-logs.txt file?

**Comment by bourdakos1** [comment]
Things look okay on my end. How many images did you label and how many labels?

**Comment by TheFeed** [comment]
1. No problem. Attached is the training log.
[training-log.txt](https://github.com/cloud-annotations/training/files/4043711/training-log.txt)

2. ~150 images with 4 labels. The labels were all different in quantity, some were only used about 50% of the time while others were in every image.

**Comment by bourdakos1** [comment]
What version of cacli are you using?

**Comment by TheFeed** [comment]
v. 1.2.24

**Comment by bourdakos1** [comment]
Just for my reference https://github.com/tensorflow/tensorflow/issues/25704

**Comment by bourdakos1** [comment]
so it should be using these versions:
```
tensorflow-1.14
tensorflowjs-0.8.0
```

I double check that the versions are compatible 

Would it be possible to send the `model` folder? I can try converting it manually

**Comment by TheFeed** [comment]
Here is a Google Drive link with the model folder:
[https://drive.google.com/open?id=1J8Ox82CXcRtIEM86jD24qdOGdPcho7Nr](url)

**Comment by bourdakos1** [comment]
I tried training again and got the same error, I'm bumping the tensorflow.js converter version which should hopefully fix the issue 🤞

**Comment by bourdakos1** [comment]
In the meantime you can try running:
```
cacli train --frameworkv 1.12
```

**Comment by bourdakos1** [comment]
This should be fixed now, update to `cacli v1.2.26` please reopen if you're still experiencing the issue

**Comment by Fedacc** [comment]
I am using `cacli version 1.2.26` and I have trained something around 330 images with 2 labels.

I run the command for training `cacli train` and `cacli download <MODEL_ID> --tfjs --coreml --tflite` but as a result I have downloaded a folder with only **model_android** and **model_ios**, the folder **model_web** is missing.

**Comment by bourdakos1** [comment]
If you run cacli download without the flags does it still not download the model_web folder?

**Comment by bourdakos1** [comment]
@Fedacc did you happen to train the model with an older version of cacli and just try to download it with the newer version?

**Comment by Fedacc** [comment]
@bourdakos1 yes I confirm I also trained the model with the newer version of cacli.
I tried running the download without flags, among the models there are
- model_android
- model_ios
- model (not model_web)

But in the **model** folder the model.json is missing.
I have uploaded the entire downloaded folder at the following link: https://ibm.box.com/s/0uzl6cstrwbc7ugsvkft6werdej4nkmb

**Comment by bourdakos1** [comment]
Can you run “cacli logs model-id” and see if there are any errors?

**Comment by Fedacc** [comment]
At the end of the logs there is this message
```
Core ML input(s): 
 [name: "Preprocessor__sub__0"
type {
  imageType {
    width: 300
    height: 300
    colorSpace: RGB
  }
}
]
Core ML output(s): 
 [name: "Postprocessor__convert_scores__0"
type {
  multiArrayType {
    dataType: DOUBLE
  }
}
, name: "concat__0"
type {
  multiArrayType {
    shape: 4
    shape: 1917
    shape: 1
    dataType: DOUBLE
  }
}
]
cannot import name 'convert_to_constants'
Unable to convert to TensorFlow.js
```
Aside from that there is a series of Warning, but nothing that says "error"

Link to complete logs file:
https://ibm.box.com/s/93v3vmbwacmurxhajcehwvwzgqfbf62f

**Comment by bourdakos1** [comment]
@Fedacc I don't have access to the file

**Comment by bourdakos1** [comment]
In the meantime, do you mind trying to train from the GUI and see if you have the same issue?

**Comment by bourdakos1** [comment]
I think I might have forgotten to push one of the changes in the release, I'll run some tests and keep you posted

**Comment by bourdakos1** [comment]
Everything should be working now :)

**Comment by Fedacc** [comment]
I downloaded the latest version and I trained again the dataset and now I can see the **model_web** directory along with the **model.json**.
Thanks for your help!

**Comment by bourdakos1** [comment]
Great! 😁
