### ISSUE TITLE
Labeling API

### ISSUE THREAD

**Issue by dorintt** [cloud-annotations/training#201]
The documentation has the following section:
```
Uploading images/labels via API
Coming soon
```
I would like to know an approximate timeline about when this will be functional. I already have a lot of labeled images and it should not be necessary to manually label again.

**Comment by bourdakos1** [comment]
The functionality is already there, I just don’t have documentation for it yet.

In the mean time you can look up how to add files to cloud object storage on ibm cloud

**Comment by bourdakos1** [comment]
@dorintt Check out this repo: https://github.com/cloud-annotations/xml2json 

It has code for:
- transforming labels into cloud annotation format
- uploading the data to your project

**Comment by bourdakos1** [comment]
We are tracking documentation updates in this issue #168

**Comment by bourdakos1** [comment]
@dorintt I finished up the documentation for uploading files via API: https://cloud.annotations.ai/docs#uploading-images-labels-via-api

If they are still blank, it may take some time to update

**Comment by dorintt** [comment]
Thanks, I imported the data using ibm_boto3 and the labels show up correctly in the web app, but after pressing train, it fails at step 0 of 500 without any error details. Could it be realated to the way I imported data or is it a separate issue?

**Comment by bourdakos1** [comment]
@dorintt responded in #202
