### ISSUE TITLE
[training failure] Backend response timeout (30s)

### ISSUE THREAD

**Issue by dorintt** [cloud-annotations/training#202]
First, training with web app:

![ibm_ca_failed](https://user-images.githubusercontent.com/40022306/75624966-39d0f500-5bc2-11ea-82aa-ae52a5e6877f.JPG)

Then training with cacli:
```
$ cacli train

Bucket panels-01

⠏ Starting training run... error Backend response timeout (30s)
```

```
$ cacli list
──────────────────────────────────────────────────────────────────────────────────────────
 name                                          model id         status          submitted 
 panels-01                                  model-1qn1nzc4      error         an hour ago 
 panels-01                                  model-mno1p33h      error         an hour ago 
 panels-01                                  model-y7lg8gi8      error         an hour ago 
 panels-01                                  model-z9od9ow4      error      36 minutes ago 
 panels-01                                  model-2iwj18c1      error      30 minutes ago 
```

```
$ cacli logs model-1qn1nzc4
error NoSuchKey: The specified key does not exist.
	status code: 404, request id: 70e8fc34-d48d-4055-9eaf-a2ea61703910, host id:
```

**Comment by bourdakos1** [comment]
That error shouldn't have anything to do with your data. I think I've seen that error before when my bucket endpoint had a typo when I was manually testing the api, but the endpoint is autogenerated for you, so you shouldn't have to worry about that.

Do you know what region your bucket is in?

**Comment by dorintt** [comment]
I am on the Lite plans for now, and I just selected the defaults for services. From IBM cloud:
```
Services(1)
Machine Learning-2z    Default    London    Machine Learning    Active

Storage(1)
Cloud Object Storage-vz    Default    Global    Cloud Object Storage    Provisioned
```

However, my "panels-01" bucket is in us-geo location with this endpoint "s3.us.cloud-object-storage.appdomain.cloud". I don't think I could have selected an European location with the Lite plan.

**Comment by bourdakos1** [comment]
hmm, that looks good to me

**Comment by playrobotics-alex** [comment]
I am getting exactly the same error...

**Comment by playrobotics-alex** [comment]
I think I found the problem.
The machine learning service is set to London location by default, while the storage is in the US.
I deleted the ML service and created a new one in Dallas location, I am no longer getting the error , the message now says "Waiting for an available GPU (this may take a while)..." which seems to be normal.

**Comment by bourdakos1** [comment]
@playrobotics-alex That's good to know! I will look into if using buckets in another region effect training, or if there is just an issue with the London region of Watson Machine Learning.

If it says `Waiting for an available GPU (this may take a while)...` that means the training job was successfully submitted :)

**Comment by bourdakos1** [comment]
I believe the issue is with the WML London instance, I'm not able to get any bucket to train with a london instance

**Comment by bourdakos1** [comment]
The issue with London has been resolved, training should work now :)
