### ISSUE TITLE
Getting and error: Backend response timeout (30s)

### ISSUE THREAD

**Issue by playrobotics-alex** [cloud-annotations/training#203]
Hello,

Trying your great tutorial I found on YouTube.
When I run "cacli train" after a30 seconds I am getting the following error:
"Starting training run... error Backend response timeout (30s)"
I am following this guide: https://cloud.annotations.ai/workshops/object-detection/6.html
And I believe I did all the steps, can you please help me understand what I am missing?

Thanks

**Comment by playrobotics-alex** [comment]
I think I found the problem.
The machine learning service is set to London location by default, while the storage is in the US.
I deleted the ML service and created a new one in Dallas location, I am no longer getting the error , the message now says "Waiting for an available GPU (this may take a while)..." which seems to be normal.

**Comment by bourdakos1** [comment]
thanks @playrobotics-alex, we'll track this in #202
