### ISSUE TITLE
Training status is pending for too long 

### ISSUE THREAD

**Issue by dorintt** [cloud-annotations/training#204]
```
──────────────────────────────────────────────────────────────────────────────────────────
 name                                          model id         status          submitted 
 panels-01                                  model-n66zyede    completed        3 days ago 
 panels-01                                  model-q2zrngco     pending     59 minutes ago 
──────────────────────────────────────────────────────────────────────────────────────────
```
The same thing shows up in the web app as well.

I don't think I've consumed all my free resources already as I've only performed one training before, however I can't be sure because the machine learning service shows this without any additional deails:
```
Current Usage
    N/A
    Lite plan services are deleted after 30 days of inactivity.
    DETAILS
```

What I did from the previous training (which was "pending" for less than 3 minutes) was to add some more images to this bucket (> 400 images now) and try to train again.

**Comment by bourdakos1** [comment]
The GPUs have had very high usage that past week, so it can take a really long time before it starts to train

**Comment by dorintt** [comment]
OK so this is normal. It would be very nice if the API would actually give a waiting estimate.

**Comment by bourdakos1** [comment]
I agree, this is a limitation of the Watson Machine Learning service (I don't have any control over). It would be nice to get a sense of how long the line is or if the usage is very high, but the only way to get this information is by asking the team :(

**Comment by bourdakos1** [comment]
I guess a hacky work around, is that I could submit a training job a few times a day and share the information as a API for the daily average queue time?

**Comment by bourdakos1** [comment]
I'm going to close this because I don't think there's much I can do to help :/
