### ISSUE TITLE
cacli train pending forever - failed to read json error

### ISSUE THREAD

**Issue by jennigato** [cloud-annotations/training#211]
After submitting a training run with `cacli train` and checking `cacli progress` I'm getting the message:

```Waiting for an available GPU (this may take a while)... error failed to read json: failed to get reader: failed to read frame header: EOF```

The training run didn't explicitly fail but it has been on `pending` status for over an hour. I tried changing to a different gpu and the error message disappears but the status is still pending for a long time. My WML region is Dallas (#76). Is it just because the GPUs are busy (#204) or is there an issue somewhere?

**Comment by bourdakos1** [comment]
it's most likely lack of GPUs
