### ISSUE TITLE
error Unsupported training framework specification, tensorflow_1.12

### ISSUE THREAD

**Issue by Mifaou** [cloud-annotations/training#212]
I connect with the command "cacli login" but when I try this command cacli train I receive an error :
error Unsupported training framework specification, tensorflow_1.12
Any help please ?

**Comment by bourdakos1** [comment]
I think you need to update cacli

**Comment by zacaintmyname** [comment]
Hey @bourdakos1, i think we need to update the `binary` on the windows tutorial page! It links to v1.2.29 instead of the current version. thus leading to errors with TF.

**Comment by bourdakos1** [comment]
ah! thank you @zacaintmyname :)

**Comment by bourdakos1** [comment]
The link should always point to the latest version now :)
