### ISSUE TITLE
training failed on cloud.annotations.ai 

### ISSUE THREAD

**Issue by softwind9** [cloud-annotations/training#213]
I followed instructions on https://cloud.annotations.ai/workshops/classification/index.html

but when I run 'cacli train', I get error msg (from cacli logs) like this:

'urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>'

can anybody help me? I don't find any document about it. 

thanks. 

the full log is as blow: 

 ~ % cacli logs model-wd5wf7ey      

training-I5_hf_RGR: Training with training/test data at:
training-I5_hf_RGR:   DATA_DIR: /mnt/data/gesture-detect
training-I5_hf_RGR:   MODEL_DIR: /job/model-code
training-I5_hf_RGR:   TRAINING_JOB: 
training-I5_hf_RGR:   TRAINING_COMMAND: cd "$(dirname "$(find . -name "start.sh" -maxdepth 2 | head -1)")" && chmod 777 ./start.sh && ./start.sh 1000
training-I5_hf_RGR: Wed May 20 01:47:20 UTC 2020: Running Tensorflow job

training-I5_hf_RGR: Collecting Cython
training-I5_hf_RGR:   Downloading Cython-0.29.18-cp36-cp36m-manylinux1_x86_64.whl (2.0 MB)
training-I5_hf_RGR: Collecting contextlib2
training-I5_hf_RGR:   Downloading contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
training-I5_hf_RGR: Collecting matplotlib
training-I5_hf_RGR:   Downloading matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl (12.4 MB)
training-I5_hf_RGR: Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/anaconda/envs/wmlce/lib/python3.6/site-packages (from matplotlib) (2.4.7)
training-I5_hf_RGR: Collecting cycler>=0.10
training-I5_hf_RGR:   Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
training-I5_hf_RGR: Requirement already satisfied: numpy>=1.11 in /opt/anaconda/envs/wmlce/lib/python3.6/site-packages (from matplotlib) (1.16.6)
training-I5_hf_RGR: Requirement already satisfied: python-dateutil>=2.1 in /opt/anaconda/envs/wmlce/lib/python3.6/site-packages (from matplotlib) (2.8.1)
training-I5_hf_RGR: Collecting kiwisolver>=1.0.1
training-I5_hf_RGR:   Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
training-I5_hf_RGR: Requirement already satisfied: six in /opt/anaconda/envs/wmlce/lib/python3.6/site-packages (from cycler>=0.10->matplotlib) (1.12.0)
training-I5_hf_RGR: Installing collected packages: Cython, contextlib2, cycler, kiwisolver, matplotlib
training-I5_hf_RGR:   WARNING: The scripts cygdb, cython and cythonize are installed in '/home/pwrai/.local/bin' which is not on PATH.
training-I5_hf_RGR:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
training-I5_hf_RGR: Successfully installed Cython-0.29.18 contextlib2-0.6.0.post1 cycler-0.10.0 kiwisolver-1.2.0 matplotlib-3.2.1
training-I5_hf_RGR: Collecting pycocotools==2.0.0
training-I5_hf_RGR:   Downloading pycocotools-2.0.0.tar.gz (1.5 MB)
training-I5_hf_RGR: Collecting coremltools==3.3
training-I5_hf_RGR:   Downloading coremltools-3.3-cp36-none-manylinux1_x86_64.whl (3.4 MB)
training-I5_hf_RGR: Collecting tfcoreml==1.1
training-I5_hf_RGR:   Downloading tfcoreml-1.1-py3-none-any.whl (44 kB)
training-I5_hf_RGR: Collecting tensorflowjs==1.4.0
training-I5_hf_RGR:   Downloading tensorflowjs-1.4.0-py3-none-any.whl (56 kB)
training-I5_hf_RGR: Collecting tensorflow-hub==0.3.0
training-I5_hf_RGR:   Downloading tensorflow_hub-0.3.0-py2.py3-none-any.whl (73 kB)
training-I5_hf_RGR: Collecting h5py==2.8.0
training-I5_hf_RGR:   Downloading h5py-2.8.0-cp36-cp36m-manylinux1_x86_64.whl (2.8 MB)
training-I5_hf_RGR: Collecting numpy==1.17.5
training-I5_hf_RGR:   Downloading numpy-1.17.5-cp36-cp36m-manylinux1_x86_64.whl (20.0 MB)
training-I5_hf_RGR: Collecting sympy==1.5.1
training-I5_hf_RGR:   Downloading sympy-1.5.1-py2.py3-none-any.whl (5.6 MB)
training-I5_hf_RGR: Collecting mpmath==1.1.0
training-I5_hf_RGR:   Downloading mpmath-1.1.0.tar.gz (512 kB)
training-I5_hf_RGR: Building wheels for collected packages: pycocotools, mpmath
training-I5_hf_RGR:   Building wheel for pycocotools (setup.py): started

training-I5_hf_RGR:   Building wheel for pycocotools (setup.py): finished with status 'done'
training-I5_hf_RGR:   Created wheel for pycocotools: filename=pycocotools-2.0.0-cp36-cp36m-linux_x86_64.whl size=274278 sha256=6cc972c4dd4231bc7443bcad0252c5ab76859eb0fdec39f6b547856878b69e20
training-I5_hf_RGR:   Stored in directory: /home/pwrai/.cache/pip/wheels/64/7a/c0/ac8f633d11a5f1a6902c72acb9fa828a2bb3639afba4e94a6c
training-I5_hf_RGR:   Building wheel for mpmath (setup.py): started
training-I5_hf_RGR:   Building wheel for mpmath (setup.py): finished with status 'done'
training-I5_hf_RGR:   Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=0e82a58ce4c6d8eec8f1f1a72b6fff85b612f06714d710a34577468815b84446
training-I5_hf_RGR:   Stored in directory: /home/pwrai/.cache/pip/wheels/e8/38/69/aa17553ad31f09ff5fa44c8a1a6c5b47e7c9261e9c7c16b9fb
training-I5_hf_RGR: Successfully built pycocotools mpmath
training-I5_hf_RGR: Installing collected packages: pycocotools, coremltools, tfcoreml, tensorflowjs, tensorflow-hub, h5py, numpy, sympy, mpmath
training-I5_hf_RGR:   WARNING: The script coremlconverter is installed in '/home/pwrai/.local/bin' which is not on PATH.
training-I5_hf_RGR:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
training-I5_hf_RGR:   WARNING: The scripts tensorflowjs_converter and tensorflowjs_wizard are installed in '/home/pwrai/.local/bin' which is not on PATH.
training-I5_hf_RGR:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
training-I5_hf_RGR:   WARNING: The scripts f2py, f2py3 and f2py3.6 are installed in '/home/pwrai/.local/bin' which is not on PATH.
training-I5_hf_RGR:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
training-I5_hf_RGR:   WARNING: The script isympy is installed in '/home/pwrai/.local/bin' which is not on PATH.
training-I5_hf_RGR:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
training-I5_hf_RGR: Successfully installed coremltools-3.3 h5py-2.8.0 mpmath-1.1.0 numpy-1.17.5 pycocotools-2.0.0 sympy-1.5.1 tensorflow-hub-0.3.0 tensorflowjs-1.4.0 tfcoreml-1.1
training-I5_hf_RGR: /////////////////////////////
training-I5_hf_RGR: // Training classification //
training-I5_hf_RGR: /////////////////////////////
training-I5_hf_RGR: 2020-05-20 01:47:57.573861: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: WARNING: Logging before flag parsing goes to stderr.
training-I5_hf_RGR: W0520 01:47:59.027134 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:1313: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.027679 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:970: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.027797 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:970: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.027885 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:914: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.028026 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:916: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.028207 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:168: The name tf.gfile.Walk is deprecated. Please use tf.io.gfile.walk instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: W0520 01:47:59.032017 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:181: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: I0520 01:47:59.032114 139770050467648 retrain.py:181] Looking for images in 'coffee'
training-I5_hf_RGR: W0520 01:47:59.032187 139770050467648 module_wrapper.py:139] From /job/model-code/src/classification/retrain.py:184: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.
training-I5_hf_RGR: 
training-I5_hf_RGR: I0520 01:47:59.039404 139770050467648 retrain.py:181] Looking for images in 'victory'
training-I5_hf_RGR: I0520 01:47:59.046477 139770050467648 resolver.py:79] Using /tmp/tfhub_modules to cache modules.
training-I5_hf_RGR: I0520 01:47:59.047822 139770050467648 resolver.py:398] Downloading TF-Hub Module 'https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1'.
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: 
training-I5_hf_RGR: Traceback (most recent call last):
training-I5_hf_RGR:     encode_chunked=req.has_header('Transfer-encoding'))
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 1262, in request
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 1308, in _send_request
training-I5_hf_RGR:     self.endheaders(body, encode_chunked=encode_chunked)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 1257, in endheaders
training-I5_hf_RGR:     self._send_output(message_body, encode_chunked=encode_chunked)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 1036, in _send_output
training-I5_hf_RGR:     self.send(msg)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 974, in send
training-I5_hf_RGR:     self.connect()
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 1415, in connect
training-I5_hf_RGR:     super().connect()
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/http/client.py", line 946, in connect
training-I5_hf_RGR:     (self.host,self.port), self.timeout, self.source_address)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/socket.py", line 724, in create_connection
training-I5_hf_RGR:     raise err
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/socket.py", line 713, in create_connection
training-I5_hf_RGR:     sock.connect(sa)
training-I5_hf_RGR: OSError: [Errno 101] Network is unreachable
training-I5_hf_RGR: 
training-I5_hf_RGR: During handling of the above exception, another exception occurred:
training-I5_hf_RGR: 
training-I5_hf_RGR: Traceback (most recent call last):
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/runpy.py", line 193, in _run_module_as_main
training-I5_hf_RGR:     "__main__", mod_spec)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/runpy.py", line 85, in _run_code
training-I5_hf_RGR:     exec(code, run_globals)
training-I5_hf_RGR:   File "/job/model-code/src/classification/retrain.py", line 1313, in <module>
training-I5_hf_RGR:     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
training-I5_hf_RGR:     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/absl/app.py", line 300, in run
training-I5_hf_RGR:     _run_main(main, args)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
training-I5_hf_RGR:     sys.exit(main(argv))
training-I5_hf_RGR:   File "/job/model-code/src/classification/retrain.py", line 998, in main
training-I5_hf_RGR:     module_spec = hub.load_module_spec(FLAGS.tfhub_module)
training-I5_hf_RGR:   File "/home/pwrai/.local/lib/python3.6/site-packages/tensorflow_hub/module.py", line 60, in load_module_spec
training-I5_hf_RGR:     path = registry.resolver(path)
training-I5_hf_RGR:   File "/home/pwrai/.local/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 42, in __call__
training-I5_hf_RGR:     return impl(*args, **kwargs)
training-I5_hf_RGR:   File "/home/pwrai/.local/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 103, in __call__
training-I5_hf_RGR:     self._lock_file_timeout_sec())
training-I5_hf_RGR:   File "/home/pwrai/.local/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 400, in atomic_download
training-I5_hf_RGR:     download_fn(handle, tmp_dir)
training-I5_hf_RGR:   File "/home/pwrai/.local/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 98, in download
training-I5_hf_RGR:     response = url_opener.open(request)
training-I5_hf_RGR: 
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/urllib/request.py", line 526, in open
training-I5_hf_RGR:     response = self._open(req, data)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/urllib/request.py", line 544, in _open
training-I5_hf_RGR:     '_open', req)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/urllib/request.py", line 504, in _call_chain
training-I5_hf_RGR:     result = func(*args)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/urllib/request.py", line 1361, in https_open
training-I5_hf_RGR:     context=self._context, check_hostname=self._check_hostname)
training-I5_hf_RGR:   File "/opt/anaconda/envs/wmlce/lib/python3.6/urllib/request.py", line 1320, in do_open
training-I5_hf_RGR:     raise URLError(err)
training-I5_hf_RGR: urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
training-I5_hf_RGR: CACLI-TRAINING-FAILED
training-I5_hf_RGR: Training exited with error code 1
training-I5_hf_RGR: Failed: learner_exit_code: 1

**Comment by bourdakos1** [comment]
This is a known issue that popped up yesterday, it seems like it only happens on classification when trying to download from tfhub, and only fails ~60% of the time. Im looking into whether it’s an issue with tfhub or a connection problem on WML’s end.

It seems to be able to download all the python packages and load images from the bucket just fine

**Comment by bourdakos1** [comment]
@softwind9 If you’re comfortable with using jupyter notebooks, you could use the “export notebook” feature as a temporary workaround.

You can run the notebook locally or import it into Watson studio/ google collab to run on a gpu

**Comment by softwind9** [comment]
@bourdakos1   Thanks for your reply. 

I'm not an expert on "Jupyter notebook", but I will try it. 

Thanks a lot.

**Comment by bourdakos1** [comment]
@softwind9 WML issued a fix, so training should work now. Feel free to reopen if you’re still having problems
