### ISSUE TITLE
creating machine-learning meets some problems

### ISSUE THREAD

**Issue by xiaozhu1697** [cloud-annotations/training#215]
Note: Cloud Annotations relies on Deep Learning as a Service which is only supported in the Dallas and Frankfurt regions.
I don't belong to these regions , can I train some pichures?

**Comment by bourdakos1** [comment]
You don’t need to live in the region to train, you just need to choose the data center in that region

**Comment by xiaozhu1697** [comment]
I can download models,and I put the   model_web  folder   into the  public  folders  ,but after I  execute the npm start,   it  can't  work correctly.    it   only  open the  camera ,  but it can't display the marks.   


![20200712203918](https://user-images.githubusercontent.com/58245378/87246546-af0dda00-c480-11ea-929c-c215f718bbe5.png)

**Comment by bourdakos1** [comment]
Are there any error messages in the web inspector?

**Comment by bourdakos1** [comment]
It might be an error that says something about tensor shape and [1917,], if so you might need more training data per label

**Comment by xiaozhu1697** [comment]
I trained over 20 to test the program ，but  when I execute the npm start ,it have  the  
![20200712231939](https://user-images.githubusercontent.com/58245378/87250386-f56e3380-c496-11ea-8265-0038b4828517.png)

**Comment by xiaozhu1697** [comment]
I press ESC at the prompt  ，it won't work, but it  can turn on the camera

**Comment by bourdakos1** [comment]
You might have trained a classification model and not an object detection model required for this demo. When labeling your photos did you draw bounding boxes?

**Comment by xiaozhu1697** [comment]
![20200713072059](https://user-images.githubusercontent.com/58245378/87258852-6d5d4d80-c4d9-11ea-9a17-2c9c9e95b12a.png)

**Comment by xiaozhu1697** [comment]
![image](https://user-images.githubusercontent.com/58245378/87258908-ce852100-c4d9-11ea-85c7-fb33812fe2ed.png)

**Comment by xiaozhu1697** [comment]
![image](https://user-images.githubusercontent.com/58245378/87258947-42bfc480-c4da-11ea-9218-ad768d5e81e4.png)

**Comment by xiaozhu1697** [comment]
I try to build a classification  ,but it still can't display the mark ,but  it can work  correctly   in the box
![20200713171457](https://user-images.githubusercontent.com/58245378/87287513-c904f680-c52c-11ea-8f8c-062b410f8294.png)

**Comment by xiaozhu1697** [comment]
I don't know the problem

**Comment by xiaozhu1697** [comment]
When I execute the npm start about the classification  , it don't have the camera , is it normal?
![image](https://user-images.githubusercontent.com/58245378/87292127-ed63d180-c532-11ea-9132-5b47534a730e.png)

**Comment by xiaozhu1697** [comment]
![image](https://user-images.githubusercontent.com/58245378/87292309-3451c700-c533-11ea-8c79-b3ddd4ed7d67.png)

**Comment by bourdakos1** [comment]
The classification demo doesn’t use the webcam, it just lets you upload an image

**Comment by xiaozhu1697** [comment]
![O@R_R@NMN`JYDLBP5ZQIVTR](https://user-images.githubusercontent.com/58245378/87651260-665a6780-c785-11ea-8c8e-f6377874e953.png)
It's been here for two days.

**Comment by bourdakos1** [comment]
Can you use the CLI to run “cacli logs <model-id>”?

**Comment by xiaozhu1697** [comment]
No , It is waiting for a  available GPU when I execute the cacli train

**Comment by bourdakos1** [comment]
Okay, there must just be high usage of the GPUs, you can try submitting another job and see if that goes through

**Comment by xiaozhu1697** [comment]
I've done it eight times, but the results are the same

**Comment by bourdakos1** [comment]
I guess all the GPUs are full then, you can try one of the non-free GPUs they some times have less usage
