### ISSUE TITLE
Unable to Log in due to connection refused on port 9000

### ISSUE THREAD

**Issue by weritmedal** [cloud-annotations/training#218]
Can't login to the software as nothing is listening on port 9000.

[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=NHEsT0A from localhost:3000 to http://localhost:9000/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/accounts from localhost:3000 to http://localhost:9000/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=NHEsTpG from localhost:3000 to http://localhost:9000/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=NHEsUw3 from localhost:3000 to http://localhost:9000/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

On login attemt:

Error occured while trying to proxy to: localhost:3000/auth/login?state=%2F

This is on Windows.   I did npm install in the src and src/client directory.

I tried running as admin too.  Netstat confirms nothing is listening on port 9000.  

Thanks!

**Comment by bourdakos1** [comment]
Did you run npm start in src? Or src/client? running in src should start up the backend on port 9000

**Comment by weritmedal** [comment]
I was running it in src/client.  If I do npm start in src, I get:

> watson-ml@0.1.0 start C:\Users\Mike\Documents\GitHub\cloud-annotations-client\src
> concurrently --kill-others-on-fail "yarn server" "yarn client"

[0] 'yarn' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'yarn' is not recognized as an internal or external command,
[1] operable program or batch file.
[0] yarn server exited with code 1
--> Sending SIGTERM to other processes..
[1] yarn client exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! watson-ml@0.1.0 start: `concurrently --kill-others-on-fail "yarn server" "yarn client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the watson-ml@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2020-09-02T13_13_52_922Z-debug.log

**Comment by weritmedal** [comment]
Oh, so I did npm -g install yarn and it worked.  Thanks!
