### ISSUE TITLE
WML V4 Migration is in progress. Training is temporarily unavailable

### ISSUE THREAD

**Issue by DeepakramKG** [cloud-annotations/training#222]
Hi,

The following message shows up when I attempt to look at the training runs 
**"WML V4 Migration is in progress. Training is temporarily unavailable"**

When I train through GUI, it is unusually taking long time and when I attempt to train using CLI, it shows the following error message 
**Unable to get /v3/wml_instances/6b78e52d-147d-4e47-881e-cd7496a2dd54 [400]: {"trace":"8fdb02ab643c548f2827e816a0f57bbf","errors":[{"code":"invalid_request","message":"Instance in v2 plan should use v4 API."}]}**

I noticed that there has been an update in the [Watson Machine Learning service](https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/whats-new.html) 
But is the Cloud annotation tool not updated to handle the latest release or is there any workaround?

**Comment by bourdakos1** [comment]
Hi @DeepakramKG, 

The Watson Machine Learning service has added a new `V4 API` and a new `V2 instance type`. A `V2 instance type` **MUST** use the `V4 API`, where a `V1 instance type` can continue to use the `V3 API`. Unfortunately, all `lite tier` `V1 instances` have been automatically migrated to `V2`. If you where paying for a `standard/professional tier` the instance would remain a `V1 instance type`. Additionally, no more `V1 instance types` can be provisioned.

I'm doing my best to migrate to the `V4 API`, but it's a lot of work and there seems to be some unresolved issues with the new API. 

In the meantime you could try using Google Colab to train your models. I have put together a notebook that runs the same training scripts as Cloud Annotations: https://colab.research.google.com/github/cloud-annotations/google-colab-training/blob/master/object_detection.ipynb

Hope this helps, sorry for the inconvenience 😕

**Comment by DeepakramKG** [comment]
Hi @bourdakos1 ,

That helps. Thank you so much. Would be lovely to see the WML V4 API migration soon.

**Comment by bourdakos1** [comment]
I've thought it over and I don't think I will make the migration to Watson Machine Learning V4. There has been too many issues with the service and it has been to difficult to maintain as one person.

Training Cloud Annotations data with Watson Machine Learning is still possible through the IBM Cloud CLI or watson studio, but there will no longer be an easy "train with watson machine learning" button in the tool.

(There's a new "train in colab" button in the tool as an alternative)
