### ISSUE TITLE
Cacli Train Command Error -macOS

### ISSUE THREAD

**Issue by sasank013** [cloud-annotations/training#224]
I am brand new to Cloud Annotations but I have done the Image Classification and training as per the documentation here: https://cloud.annotations.ai/workshops/classification/7.html

On the command 
$ cacli train

I am getting this error

Starting training run... error Unable to get /v3/wml_instances/eb1fa779-607c-4d6b-ab0f-61c11bfb16aa [400]: {"trace":"4e89c1475002a38642e17f52720f4588","errors":[{"code":"invalid_request","message":"Instance in v2 plan should use v4 API."}]}

What should I be doing different?

**Comment by bourdakos1** [comment]
Hi there, your watson machine learning instance is `v2` which isn't compatible with cloud annotations at the moment. The best option is to use the `train in colab` button in the UI

**Comment by sasank013** [comment]
is there any way to change the learning instance or update something

**Comment by bourdakos1** [comment]
No sorry :( 

all new instances are v2 as of September 1st. I’m doing my best to migrate, but there have been a lot of issues.

We are tracking the migration in this issue: https://github.com/cloud-annotations/training/issues/222
