### ISSUE TITLE
Unable to load images from a specific bucket from IBM Cloud Object storage.

### ISSUE THREAD

**Issue by charles2588** [cloud-annotations/training#237]
Unable to load images from a specific bucket from IBM Cloud Object storage.
![image](https://user-images.githubusercontent.com/5734421/103565299-f9db3e00-4e74-11eb-94c8-44cc02598ede.png)

@bourdakos1 FYI

**Comment by bourdakos1** [comment]
It looks like the images are stored at paths with multi-bit characters. For example, `炒小卷.zip`. I will look into how COS expects you to fetch for this path. Right now I urlencode the path which results in `%E7%82%92%E5%B0%8F%E5%8D%B7.zip` which it doesn't seem to accept

**Comment by bourdakos1** [comment]
should be fixed now :)
