### ISSUE TITLE
[CLI] Local training via Docker containers

### ISSUE THREAD

**Issue by moficodes** [cloud-annotations/training#33]
feature-
For local training use a docker images and train.

**Comment by ramprasad66** [comment]
Ok Thanks

**Comment by bourdakos1** [comment]
No problem @ramprasader66

**Comment by srctar** [comment]
if there is someone tell me how to run this project with my own computer?

**Comment by bourdakos1** [comment]
@srctar We don't have out of the box support for this yet, but what you can do is clone this project and run the start script under `trainer/src`  (you will need to download the contents of your bucket first and set a command line flag `DATA_DIR` to point to the bucket contents and then another flag `RESULT_DIR`)

**Comment by bourdakos1** [comment]
@srctar I haven't tested this but... try this:
clone the repo and change into `trainer/src`:
```
git clone https://github.com/cloud-annotations/training
cd training/trainer/src
```

Download the contents of your bucket:
```
cacli export
```

Set training flags:
```
export DATA_DIR="exported_buckets/<bucket_name>"
export RESULT_DIR ="exported_buckets"
```

Run the training script:
```
./start.sh
```

**Comment by bourdakos1** [comment]
> **Update:** I tried running and this won't work because you need to build the package first. It's probably easier to just download the training zip release: https://github.com/cloud-annotations/training/releases/download/v1.1.0/training.zip

and then change the permission of the script to executable:
```
sudo chmod +x start.sh
```

**Comment by srctar** [comment]
> > **Update:** I tried running and this won't work because you need to build the package first. It's probably easier to just download the training zip release: https://github.com/cloud-annotations/training/releases/download/v1.1.0/training.zip
> 
> and then change the permission of the script to executable:
> 
> ```
> sudo chmod +x start.sh
> ```
> 
> and then run:
> 
> ```
> ./start.sh <number-of-training-steps>
> ```

Thanks a lot。 
I just had a try, but I`m a newer for machine learning, also a newer for python.
I don`t know what should I do to prepare for this project, 
so, mark now, I`m going to learn about this, then do this again

**Comment by bourdakos1** [comment]
@moficodes any progress on this?

**Comment by bourdakos1** [comment]
I don't think this will be on our roadmap anymore
