### ISSUE TITLE
 Add choose Annotation type screenshot in walkthroughs

### ISSUE THREAD

**Issue by mkriznjak** [cloud-annotations/training#38]
Please, just add a step after clicking on Create bucket that user need to chose Annotation type Localization

**Comment by bourdakos1** [comment]
Any reason why this was closed? This is a valid issue, a lot of people get tripped up on this. I’ll add a screenshot in the documentation.

**Comment by bourdakos1** [comment]
added a substep with image to the walkthrough which describes which annotation type to choose:
https://cloud-annotations.github.io/training/object-detection/cli/5.html
