### ISSUE TITLE
[CLI] Add support for cancelling training runs

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/training#41]

**Comment by datamonday** [comment]
Can it work now?

**Comment by bourdakos1** [comment]
not yet

**Comment by sachinshelke** [comment]
@bourdakos1 is there any way to cancel training.
Don't know why but my training was running since last 5 days and not yet completed.

Whenever i check `cacli progress model-id` it is very slow and only ~1968 / 200000 steps are showing.

**Comment by sachinshelke** [comment]
Tried with bx ml cancel training-runs {model-id}.
It works.

**Comment by bourdakos1** [comment]
I’m working on rewriting the CLI in go, It should be a first class feature when released

**Comment by bourdakos1** [comment]
implemented in new golang CLI
