### ISSUE TITLE
not able to login to the Cloud Annotation Storage web

### ISSUE THREAD

**Issue by pragyakirti** [cloud-annotations/training#52]
I am unable to login to the Cloud Annotations Tool to add images in the bucket.  ResouceInstanceID and APIKey from the object storage credentials are not accpted and  nothing happens after clicking “continue” button.  What am I doing wrong?  Should I change Endpoint? If I am not able to get past the authentication page, is there any way around this webUI tool. 
Please help.

Cheers, 
Pragya

**Comment by bourdakos1** [comment]
My guess is that your instanceId is incorrect, make sure you copy over the last 2 colons at the end of the is “::” a lot of people miss those

**Comment by bourdakos1** [comment]
If not send me a private message with your credentials and I’ll try to help out

**Comment by pragyakirti** [comment]
I solved the issue and now following next steps to label and then train the model. Let see how far I go.  Thanks for your prompt reply and support. I will close this issue now.

**Comment by pragyakirti** [comment]
I solved the issue and now following next steps to label and then train the model. Let see how far I go.  Thanks for your prompt reply and support. I will close this issue now.

**Comment by bourdakos1** [comment]
Great :) Do you mind mentioning what fixed the issue?

**Comment by Anysh** [comment]
> My guess is that your instanceId is incorrect, make sure you copy over the last 2 colons at the end of the is “::” a lot of people miss those

Hey, I'm facing the same issue. I'm copying till 2 colons, It's doesn't continue to next page. Even after trying, again and again, API Key gets vanish and I'm stuck again on the same page.

**Comment by bourdakos1** [comment]
@Anysh are you just copying until the 2 colons, or including the 2 colons? make sure you include them. I've also seen a couple people with issues logging in with Firefox so try using Chrome if you aren't already

**Comment by Anysh** [comment]
Including 2 colons* Still not working in Safari. But it worked in Chrome. Thanks :)

**Comment by bourdakos1** [comment]
good to know, not sure why some people have issues with non chrome browsers, It works on safari for me, what version of safari do you have?

**Comment by Anysh** [comment]
Version 11.1

**Comment by bourdakos1** [comment]
I have version 12.1 I wonder if thats the issue
