### ISSUE TITLE
Cloud Annotations: Labels not saved properly with multiple editors

### ISSUE THREAD

**Issue by michael-may** [cloud-annotations/training#55]
We've had some problems with changes not being saved properly in cloud annotations if multiple people are drawing boxes at the same time.

I haven't been able to track down the exact behavior, but here's a flow that it seems like has triggered it:

- User 1 logs in and starts annotating images.
- User 1 steps away and leaves the tab open.
- User 2 starts annotating images.
- User 1 returns and resumes annotating.
- User 2's changes are lost as User 1's changes are saved.

This happens even if users log in with different API keys.

Let me know if there are any known workarounds, or if any more testing would be helpful.

**Comment by bourdakos1** [comment]
We don’t really have support for multi user collaboration yet. The tool is still in a very early beta, but collaboration is something I’d really like to get added in ASAP, especially if it’s at the level already where people are expecting it. Getting this up to a google docs level of collaboration will probably take a good chunk of time, but I should be able to get it to the point where you aren’t overriding everyone’s changes, as long as you aren’t working on the same image, by the end of next week.

If you have some time next week, I’d love to have a discussion about your needs from the tool to help guide it in the right direction out of beta 😁

**Comment by michael-may** [comment]
I think that sounds like a reasonable compromise, especially with such a quick turnaround.

I can totally walk you through our ideal workflow! Just let me know how you want to go over it.

**Comment by bourdakos1** [comment]
@michael-may I think I have an update ready, just want to test it a bit more before deploying. You can email me at bourdakos1@gmail.com and we can set up a call or something :)

**Comment by bourdakos1** [comment]
multi-user support is now in production. Let's open up new issues if any subsequent problems arise :)
