### ISSUE TITLE
command error by Running npm 

### ISSUE THREAD

**Issue by AnsMumtaz** [cloud-annotations/training#57]
npm install -g cloud-annotations

when i run this command, its gives error that command doesn't found... i dont know how to make it run

**Comment by bourdakos1** [comment]
Make sure you have node installed

**Comment by AnsMumtaz** [comment]
this is the error... node is installed with version 6.4.1

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-04-26T10_42_16_004Z-debug.log

**Comment by bourdakos1** [comment]
Oh, you need node version 10+ and if it still doesn’t work and gives you permission errors try running with sudo, but you really shouldn’t have to unless node/npm was set up in a weird way

**Comment by AnsMumtaz** [comment]
thanks it worked with sudo

**Comment by AnsMumtaz** [comment]
1) i have 4 classes Speed 20, 30 , 50, 60.....i have uploaded 400 images for annotations... there is no option... how can i annotate my data(which is already in bucket).

2) for training: which "url" is needed ?

**Comment by bourdakos1** [comment]
Did you choose classification instead of localization? If so, you need to delete that bucket and create a new one, or modify the _annotations.json file to "localization"

**Comment by bourdakos1** [comment]
I'm going to close this issue, feel free to open another issue regarding your new question about annotating the data
