### ISSUE TITLE
Training was canceled or failed.

### ISSUE THREAD

**Issue by michaelpimentel88** [cloud-annotations/training#58]
After training is complete. Then running cacli download <model_id>
id get 

> `Training was canceled or failed.`

**Comment by bourdakos1** [comment]
Correct me if I'm wrong, but I think you resolved this by adding bounding boxes to your images in the Cloud Annotation tool.

**Comment by michaelpimentel88** [comment]
yeah thanks for that! Turns out you do need 20+ images.
