### ISSUE TITLE
ibmcloud login password prompt not working

### ISSUE THREAD

**Issue by bcstarke** [cloud-annotations/training#61]

**Comment by bcstarke** [comment]
I was able to follow the tutorial successfully until step 5. I am having difficulty using the installed Cloud Annotation CLI. When I run ibmcloud login on Powershell the username prompt works fine, but the password prompt won't let me type in a password. 
I'm running this on Windows 10 Home.

**Comment by bourdakos1** [comment]
You don’t need to run ibmcloud login

**Comment by bcstarke** [comment]
Thanks for the quick reply. I was able to get past it. I am trying to run cacli train and while entering my credentials I must have made a typo because I get an error message saying Invalid Watson Machine Learning credentials. It does not appear to be letting me reenter the credentials. Do you know a way around this? Thanks!

**Comment by bcstarke** [comment]
Nevermind, figured it out!

**Comment by bourdakos1** [comment]
haha okay :) I'll go ahead and close this then

**Comment by vincycode7** [comment]
Hello, I am getting an error when i type cacli train

**Comment by Aabhaskarnawat** [comment]
> Nevermind, figured it out!

i am also facing the same problem...can u please explain how u hv reset the credentials

**Comment by bourdakos1** [comment]
Cacli init
