### ISSUE TITLE
Screenshot Update - PRs welcome?

### ISSUE THREAD

**Issue by GantMan** [cloud-annotations/training#62]
current screenshot is for HMAC setting is:
![image](https://user-images.githubusercontent.com/997157/57293182-3b29b200-70c4-11e9-91f7-9f9ba99564f1.png)

Would it be ok if I update it and outline in red the new UI with this image?
![image](https://user-images.githubusercontent.com/997157/57293232-5a284400-70c4-11e9-9b74-f2a6e7ba4c36.png)

Or does it need to be full-screen size like this?
![image](https://user-images.githubusercontent.com/997157/57293262-75934f00-70c4-11e9-96a7-ad7505f8f70b.png)

Let me know which one, and if it's ok for me to submit a PR.

**Comment by bourdakos1** [comment]
PRs welcome, but I think I want to hold off on updating this just yet. I don't think this is fully rolled out yet and not everyone get's this new UI. Also, if you have a mac, I like to use a screenshot of a chrome incognito browser with the drop-shadow/rounded corners (⌘+Shift+4 space)

**Comment by GantMan** [comment]
k.  Circle back and tag me if you'd like me to do it.
