### ISSUE TITLE
Issue using cacli after "npm g cloud annotations"

### ISSUE THREAD

**Issue by vincycode7** [cloud-annotations/training#65]
I am having issue using cacli as it is giving an error when it is about to run the init.js file on my Ubuntu.

**Comment by bourdakos1** [comment]
What is the error?

**Comment by vincycode7** [comment]
![Screenshot from 2019-05-09 18-40-20](https://user-images.githubusercontent.com/41131516/57573322-dfda2580-741d-11e9-8475-e85e147064fe.png)

**Comment by vincycode7** [comment]
That was the error i was getting

**Comment by bourdakos1** [comment]
I think you need to update node, also update cacli. There’s a new version that will tell you to update node if you don’t have the correct version :)

**Comment by vincycode7** [comment]
Thank you, That worked.
