### ISSUE TITLE
cacli info not returning anything

### ISSUE THREAD

**Issue by deerdear** [cloud-annotations/training#66]
When running `cacli info <MODEL-ID>` I don't get a return.

It would be great to get model information like number of samples, runs, what type of model etc.

**Comment by deerdear** [comment]
Realised `info` isn't a valid command... `log` probably covers the important parameters, otherwise it can be opened to be a feature request

**Comment by bourdakos1** [comment]
cacli info isn't a command yet, but it's on the roadmap to give some more internal WML information like model local in the object storage bucket
