### ISSUE TITLE
About the model file output

### ISSUE THREAD

**Issue by datamonday** [cloud-annotations/training#72]
Will the object detection model support the output of the original model file or caffemodel after training, instead of supporting the ios, android, web model files?

**Comment by bourdakos1** [comment]
In the future yes, it will automatically download the tensorflow graph. As of now it only downloads the core ml, tflite, and tfjs files. You can still access the original graph in the object storage bucket (whatever bucket you set as the output)

**Comment by datamonday** [comment]
@bourdakos1  Thank you very much for your patience and timely answers.
