### ISSUE TITLE
About training object detection model

### ISSUE THREAD

**Issue by datamonday** [cloud-annotations/training#73]
When using the ibm cloud gpu training model, is the number of training iterations automatically determined? Yesterday, my training model only trained 500 steps, and I feel that the performance is not good. Can I manually set the number of training iterations? thanks!

**Comment by bourdakos1** [comment]
500 is just the default, you can change the settings by running `cacli init` I recommend training for about 20 * the number of images

**Comment by oumingyang** [comment]
I think it can be manually set.
![图片](https://user-images.githubusercontent.com/29618441/57838194-d1618480-77f6-11e9-954d-da620aec389c.png)
