### ISSUE TITLE
Do you have the user guide step by step since I cannot realize this project

### ISSUE THREAD

**Issue by ztr1918294** [cloud-annotations/training#75]
I am a new guy for doing this.
1st, I installed Node.js
2nd, I used command 'npm install -g create-react-app yarn' to install yarn
3rd, I used command ' create-react-app react-app' to creat the react-app folder
4th, I entered into the folder 'react-app', and used command 'yarn start', then the broser went to  http://localhost:3000, and I saw 'Welcome to React'.
5th, but when I copy all the files on 'https://github.com/cloud-annotations/training' to the folder 'react-app', and used command 'yarn start', then the error showed up. It looks like the words in index.js
if (process.version.match(/v(\d+)\./)[1] < 10) {
  console.log(
    `Node version 10 or later is required. Not satisfied by current version ${
      process.version
    }.`
  )
  return process.exit(1)
}
But my node.js version is V10.15.3, my yarn version is 1.16.0
Then I delete those code, then restart, the error showed up.
./src/utils/picker.js
Line 58: rl is not defined no-undef

I do not know why. How can I realize your project?
Hope you can send me email ztr1918294@163.com. Thank you very much!

**Comment by bourdakos1** [comment]
https://cloud-annotations.github.io/training/object-detection/cli/

**Comment by ztr1918294** [comment]
I downloaded the .zip from 'https://github.com/cloud-annotations/training' and unzipped it, then I got all the files.
I used command 'npm install'
Then I used command 'yarn start', but error comes out 'Command "start" not found'
If your example on 'https://github.com/cloud-annotations/training' is good and can be realized, why can not I realize the performance as you did? Should I use other command like 'npm XXX' since in file 'package.json' the scripts does not have "start". 
"scripts": {
    "test": "nyc mocha \"__tests__/**/*.test.js\"",
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    "build": "cd trainer && python setup.py all",
    "alias": "sed -i '' '/alias cacli-dev=/d' ~/.bashrc && echo \"alias cacli-dev=\\\"$PWD/bin/cacli\\\"\" >> ~/.bashrc",
    "patch": "./publish-trainer.sh $(npm --no-git-tag-version version patch) && yarn publish"
  },
I do not know what XXX is.

**Comment by ztr1918294** [comment]
I did as the site 'https://cloud-annotations.github.io/training/object-detection/cli' told.
I upload your 'training_video.mp4' and label some images as car.
And after I used command 'cacli train' and input all the credentials, then 'Start training run...' showed up. But 3 hours went on, it still stops at 'Start training run...', is it normal?

**Comment by bourdakos1** [comment]
I think you cloned the wrong repo
