### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Mahibro** [cloud-annotations/training#77]
Not connecting to cloud storage.Used API key but still connection problem.

**Comment by bourdakos1** [comment]
can you give some more details? was this through cacli or are you having trouble accessing the GUI?

**Comment by Mahibro** [comment]
@bourdakos1 
I have installed (npm install -g cloud-annotations) in my local machine,after that when i try to do (cacli train) is not happening??can you tell me what is the problem?

**Comment by bourdakos1** [comment]
Do you get an error? Can you send a screenshot

**Comment by Mahibro** [comment]
This is my local machine.
1) (I have installed this)
https://cloud-annotations.github.io/training/object-detection/cli/7.html
2) When i submit training ( calci train ) , it saying that command is not
found.How do i fix this?

**Comment by bourdakos1** [comment]
It must have not installed/installed properly, did you get an error message when installing?

**Comment by kanwanwomingzidedoushisb** [comment]
I met the same problem.  I run the object detection successfully yesterday but when tried classification, after put instance ID&api key(I'm sure that it's correct) , cannot get to my annotation page.

**Comment by kanwanwomingzidedoushisb** [comment]
finally I made it by recreate an object storage instance and machine learning instance.  can't believe as a product manager I can run this:) thanks.
