### ISSUE TITLE
The value of resource should be either k80, k80x2, k80x4, v100 or v100x2"

### ISSUE THREAD

**Issue by kurish** [cloud-annotations/training#79]
Hi man
When i'm trying to "cacli train" i have error

StatusCodeError: 400 - {"trace":"abe3e9362a437359546df3f0a4a1a2e1","errors":[{"code":"training_failed","message":"Manifest Error: The value of resource should be either k80, k80x2, k80x4, v100 or v100x2","more_info":"http://watson-ml-api.mybluemix.net/"}]}

mb some advices?

also, after we fix it, how can i convert downloaded model for using with tensorflowjs-node?

many thanks!

**Comment by bourdakos1** [comment]
Try running `cacli init` and make sure gpu is one of those options

**Comment by kurish** [comment]
Many thanks
