### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hangwin** [cloud-annotations/training#81]
i took many photos of my hand to make a dataset ,but it always recognize wrong,can you share your dataset of the emoji demo?

**Comment by bourdakos1** [comment]
you can try bumping the amount of training steps. How many images did you use per label?

**Comment by hangwin** [comment]
100 per label

**Comment by hangwin** [comment]
and when i use other things(eg: a mobile phone) to make a dataset，it seems right

**Comment by bourdakos1** [comment]
It's normally easier to train for mobile phones and other simple objects, hands can be difficult. I recommend keep adding more images and train for more steps. If you have 100 images per label, and let's say 5 labels, try training for 10,000 steps
