### ISSUE TITLE
error Invalid training bucket

### ISSUE THREAD

**Issue by vanderstelTroy** [cloud-annotations/training#87]
Im getting the error 'Invalid training bucket' after running cacli train and entering my credentials.

Any idea why this might be happening?

**Comment by bourdakos1** [comment]
Did it let you choose a bucket?

**Comment by vanderstelTroy** [comment]
It was my own mistake, was giving the wrong location for the test bucket, i thought it was just eu but seemed to be eu-de.

**Comment by bourdakos1** [comment]
Ah gotcha, I’ll go ahead and close this then
