### ISSUE TITLE
the image file name changed 

### ISSUE THREAD

**Issue by Chloejay** [cloud-annotations/training#90]
when I upload the image to cloud annotation, the returned json fille, the image name changed(with `-`), and can't matched with my image file name from s3 bucket, even I tried to replace `-`, anyone knows the reason or how the name changes or its possible to keep the same image for IO file? so that I can use this to compare the model inference result. the image name in s3 bucket is like this `7289cf25eba896cae13bb295b99d9164.jpg` 
![image](https://user-images.githubusercontent.com/24205486/60122957-e861a200-97b8-11e9-9ae5-4271251f25fa.png) 

for example I tested two images, the names are totally changed 
<img width="757" alt="Screen Shot 2019-06-26 at 16 51 33" src="https://user-images.githubusercontent.com/24205486/60165992-e9cfb080-9832-11e9-92d9-d6374b1bb35b.png">

**Comment by bourdakos1** [comment]
Cloud Annotations generates a UUID for the images you upload through the GUI to avoid collisions. You can use `cacli bootstrap` or the COS rest api to upload files to the bucket without the names being changed. Is there a reason you need the image names to match the bucket names?

**Comment by Chloejay** [comment]
yes the reason why I need keep the image name same, is for my model inference purpose, I trained model on aws EC2, on inference phase I directly connect s3 bucket for the images I stored there; then for the ground truth labelling, I need to use image tag, but if name is not consistent, I can't use to compare and plot like ROC curve or even calculate the precision and recall value for model evaluation

**Comment by bourdakos1** [comment]
gotcha, the image names are stable once you upload them. Can you just use the new names?

**Comment by Chloejay** [comment]
its possible, but on this case which is not very functional to make use of aws s3 bucket

**Comment by bourdakos1** [comment]
Do you need to use the aws s3 bucket? If the are already in the ibm bucket?

**Comment by Chloejay** [comment]
> Do you need to use the aws s3 bucket? If the are already in the ibm bucket?

yes there are already in ibm bucket which I uploaded the images that downloaded from aws s3 bucket, I think based on the enterprise infra I need to use the s3 bucket at the moment, is there any option I can directly fetch all the images from s3 bucket and do the annotation and labeling?

**Comment by bourdakos1** [comment]
AWS S3 and IBM COS use the same exact api so you should be able to use them interchangeably. If you swap your aws s3 credentials for the ibm credentials, it should be able to pull the data. Likewise for the Cloud Annotations GUI. If you swap your ibm credentials for aws credentials it would work as well, but the endpoint in the GUI is hard coded to the ibm endpoint so you would need to modify the source and build manually

**Comment by Chloejay** [comment]
> AWS S3 and IBM COS use the same exact api so you should be able to use them interchangeably. If you swap your aws s3 credentials for the ibm credentials, it should be able to pull the data. Likewise for the Cloud Annotations GUI. If you swap your ibm credentials for aws credentials it would work as well, but the endpoint in the GUI is hard coded to the ibm endpoint so you would need to modify the source and build manually

okay will check and modify this, thanks @bourdakos1
