### ISSUE TITLE
Training exited with error code 126

### ISSUE THREAD

**Issue by bsbechtel** [cloud-annotations/training#94]
I'm seeing the following error when I try to train a model:

```
Sun Jul 21 21:02:29 UTC 2019: Running Tensorflow job
/usr/local/bin/train.sh: line 38: ./start.sh: Permission denied
Training exited with error code 126
Failed: learner_exit_code: 126
```

I double checked the credentials I have set on the bucket and machine learning instance, and don't see any issues. I'm uploading the model to the same bucket as the training data as well. Any ideas? Thanks

**Comment by bourdakos1** [comment]
I’ve seen a couple get this error today, I’ll check it out

**Comment by bourdakos1** [comment]
Should be fixed if you update cloud annotations cli

**Comment by bsbechtel** [comment]
It's working. Thanks for the quick response!
