### ISSUE TITLE
not getting any objects detected

### ISSUE THREAD

**Issue by talarari** [cloud-annotations/training#96]
i followed this guide
https://cloud-annotations.github.io/training/object-detection/cli/index.html

everything went well,  i labeled around a 150 images , every label has between 20-50 samples
when i download the model for android (or web) it all runs but i get no objects detected at all, scores are around 0.003 or at the highest so nothing is remotely close to the threshold.
i'm not sure what i'm doing wrong, how would you recommend i proceed?

**Comment by mdunlop2** [comment]
Same also. Have been pulling my hair out over this! I trained for 50,000 steps, 168 images, 1 class (registration plate) which occurs median of 2 times per image.
```
==Input details ==
name: Preprocessor/sub
shape: [  1 300 300   3]

Get two things in output:
== Output 0 details ==
name: concat
index: 167
shape: [   1 1917    1    4]
type: <class 'numpy.float32'>

== Output 1 details ==
name: Postprocessor/convert_scores
index: 165
shape: [   1 1917    2]
type: <class 'numpy.float32'>
Prediction results shape: (1917, 2)
```

Convert the second output to pandas dataframe:
```
output_data = np.squeeze(interpreter.get_tensor(output_details[1]['index']))

print("Prediction results shape: {}".format(output_data.shape) )
temp_df = pd.DataFrame(output_data)
temp_df.describe()
```

With output:
```

             | 0                | 1
---------------------------------
COUNT: 1917.000000 | 1.917000e+03
MEAN:   0.999979      | 2.136638e-05
STD:      0.000139      | 1.342495e-04
MIN:       0.994490     | 0.000000e+00
25%:      0.999983      | 5.960464e-08
50%:      0.999999      | 1.192093e-06
75%:      1.000000      | 1.761317e-05
MAX:     1.000000      | 5.328715e-03
```

First column represents class, second represents confidence (from imageClassifier.java in android/tflitecamerademo) 

Perhaps there is a quantisation step we are missing that is included in the java `org.tensorflow.lite.Interpreter`?

I have managed to get this to work using the old `https://github.com/bourdakos1/Custom-Object-Detection/ ` however that model was too slow for my application.

Any help welcome

**Comment by bourdakos1** [comment]
@mdunlop2 I’m not sure if I understand what your table represents?

**Comment by mdunlop2** [comment]
@bourdakos1  thank you for your reply.

I'll put it in context:

```
import tensorflow as tf
import numpy as np
import pandas as pd

import os
import PIL
from PIL import Image

def load_image_into_numpy_array(image):
    (im_width, im_height) = image.size
    return np.array(image.getdata()).reshape(
        (1,im_height, im_width, 3)).astype(np.float32)

# model_path = "extractor/models/ibm_mobilenet/model_android/model.tflite"
model_path =  "/path_to_downloaded_model/model_android/model.tflite"

interpreter = tf.lite.Interpreter(model_path)
interpreter.allocate_tensors()
# obtaining the input-output shapes and types
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# understanding input format
print("== Input details ==")
print("name:", interpreter.get_input_details()[0]['name'])
print("shape:", interpreter.get_input_details()[0]['shape'])
# print("type:", interpreter.get_input_details()[0]['dtype’])

# understanding output format
print("\n== Output 0 details ==")
print("name:", interpreter.get_output_details()[0]['name'])
print("index:", interpreter.get_output_details()[0]['index'])
print("shape:", interpreter.get_output_details()[0]['shape'])
print("type:", interpreter.get_output_details()[0]['dtype'])

print("\n== Output 1 details ==")
print("name:", interpreter.get_output_details()[1]['name'])
print("index:", interpreter.get_output_details()[1]['index'])
print("shape:", interpreter.get_output_details()[1]['shape'])
print("type:", interpreter.get_output_details()[1]['dtype'])

input_img = Image.open("path_to_jpg_image")
img_column, img_row = 300, 300
input_img = input_img.resize((img_row, img_column))

x_matrix = load_image_into_numpy_array(input_img)
input_data = x_matrix.reshape(input_details[0]['shape'])
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = np.squeeze(interpreter.get_tensor(output_details[1]['index']))

print("Prediction results shape: {}".format(output_data.shape) )
temp_df = pd.DataFrame(output_data)
temp_df.describe()
```

I thought that the output represented a table with two columns: class label and class probability (I have only one label) and 1917 rows (for each anchor).

`temp_df.describe()` simply provides summary statistics of the table.

The problem is that the maximum probability of the class is 5e-03. I have tested mobilenet_v1_224 from the tensorflow model zoo and have been able to extract class probabilities in a similar manner.

Maybe my interpretation of the `interpreter.get_tensor(output_details[1]['index'])` call is incorrect?

**Comment by bourdakos1** [comment]
Oh make sure the pixel values are from 0->1 not 255

**Comment by mdunlop2** [comment]
Apologies for the late reply, can confirm that altering my previous code to
`
x_matrix = load_image_into_numpy_array(input_img).astype('float32') / 255
`
Results in successful predictions, thank you very much!

**Comment by bourdakos1** [comment]
I think float32 should be okay :)
