### ISSUE TITLE
[Trainer] Quantized model support

### ISSUE THREAD

**Issue by imokya** [cloud-annotations/training#98]
can we reduce the generated model file size? it takes too much time on loading from a web server.

**Comment by imokya** [comment]
@bourdakos1 thanks for the reply
Could u give me  a clue on how to quantize the model for mobile web？ Do you have plan to make quantization a part of calic tool ? thanks.

**Comment by sachinshelke** [comment]
hi @bourdakos1,
any updates on this. my current converted web_model is of about 23MB in size.
**Request you to please add quantize functionality for model.** 
23MB downloads took too much time.

**Comment by bourdakos1** [comment]
To be honest, quantized model support isn’t on my immediate road map, I’ve been very busy working on the cloud annotations GUI lately. However, I’m happy to merge any pull requests that add the feature. The TensorFlow object detection api has support so it shouldn’t be too difficult to add

**Comment by bourdakos1** [comment]
In the mean time you can follow this to create a quantized ssd model instead of faster rcnn

**Comment by bourdakos1** [comment]
see issue #49
